export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  PLANS: '/plans',
  PLANS_ANNUAL: '/plans/annual',
  PLANS_TRIMESTER: '/plans/trimester',
  PLANS_BIWEEKLY: '/plans/biweekly',
  PLANS_LESSON: '/plans/lesson',
  PLANS_NEW: '/plans/new',
  PLANO_ANUAL: '/plano-anual',
  PLANO_ANUAL_NEW: '/plano-anual/new',
  /** @deprecated Use PLANO_ANUAL */
  DOSIFICACAO: '/plano-anual',
  /** @deprecated Use PLANO_ANUAL_NEW */
  DOSIFICACAO_NEW: '/plano-anual/new',
  REPORTS: '/reports',
  REPORTS_NEW: '/reports/new',
  REPORTS_TRIMESTER: '/reports?type=TRIMESTER',
  REPORTS_ANNUAL: '/reports?type=ANNUAL',
  ACTIVITIES: '/activities',
  ACTIVITIES_NEW: '/activities/new',
  CALENDAR: '/calendar',
  ADMIN: '/admin',
  ADMIN_TEACHERS: '/admin/teachers',
  ADMIN_PLANS: '/admin/plans',
  SETTINGS: '/settings',
  PROFILE: '/profile',
} as const;

export const API_ROUTES = {
  AUTH: '/api/auth',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_REGISTER: '/api/auth/register',
  AUTH_LOGOUT: '/api/auth/logout',
  AUTH_REFRESH: '/api/auth/refresh',
  AUTH_ME: '/api/auth/me',
  AUTH_FORGOT_PASSWORD: '/api/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_CHANGE_PASSWORD: '/api/auth/change-password',
  AUTH_CHANGE_PASSWORD_CONFIRM: '/api/auth/change-password/confirm',
  AUTH_VERIFY_EMAIL: '/api/auth/verify-email',
  AUTH_RESEND_CODE: '/api/auth/resend-code',
  AUTH_PROFILE: '/api/auth/profile',
  AUTH_ONBOARDING: '/api/auth/onboarding',
  CALENDAR: '/api/calendar',
  CALENDAR_EVENTS: '/api/calendar/events',
  PLANS: '/api/plans',
  PLANS_GENERATE: '/api/plans/generate',
  PLANO_ANUAL: '/api/plano-anual',
  PLANO_ANUAL_IMPORT: '/api/plano-anual/import',
  /** @deprecated Use PLANO_ANUAL */
  DOSIFICACAO: '/api/plano-anual',
  REPORTS: '/api/reports',
  REPORTS_GENERATE: '/api/reports/generate',
  ACTIVITIES: '/api/activities',
  ADMIN_STATS: '/api/admin/stats',
  ADMIN_TEACHERS: '/api/admin/teachers',
  ADMIN_ALL_PLANS: '/api/admin/plans',
  AI: '/api/ai',
  USERS: '/api/users',
} as const;
